apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: aryaman-dummy-apis
  description: A collection of all APIs in Aryaman's Dummy Backstage
spec:
  targets:
    - ./apis/aryaman-api-1.yaml
