apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: aryaman-db
  description: Stores details for members in Aryaman's dummy Backstage
spec:
  type: database
  owner: platform-team
  system: aryaman-portal
