apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: The acme-corp organization for Aryaman's Dummy Backstage
  links:
    - url: http://www.acme.com/
      title: Website
    - url: https://meta.wikimedia.org/wiki/
      title: Intranet
spec:
  type: organization
  profile:
    displayName: ACME Corp for Aryaman's Dummy Backstage
    email: info@example.com
    picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: aryaman-dummy-groups
  description: A collection of all Groups in Aryaman's Dummy Backstage
spec:
  targets:
    - ./platform-team.yaml
