apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Platform Team
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: platform-team@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: acme-corp
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: test.member
spec:
  profile:
    # Intentional no displayName for testing
    email: test-member@example.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [platform-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: manik.dham
spec:
  profile:
    displayName: Manik Dham
    email: manik.dham@rupeek.com
    picture: https://media-exp1.licdn.com/dms/image/C5103AQEMy4SQPb_5Cw/profile-displayphoto-shrink_200_200/0/1567361767249?e=1649894400&v=beta&t=cTUqaXrcw6mrPD1Wxj1-sIA-aiBoC2Yzb9PG1iVqk0U
  memberOf: [platform-team]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: tejas.deshmukh
spec:
  profile:
    displayName: Tejas Deshmukh
    email: tejas.deshmukh@rupeek.com
    picture: https://cdn.vox-cdn.com/thumbor/TjSv6GUYVKeXAnmb1ltpvmh600E=/1400x1400/filters:format(jpeg)/cdn.vox-cdn.com/uploads/chorus_asset/file/23024343/CBP_e001_0239_0003.jpg
  memberOf: [platform-team]
---
# This user is added as an example, to make it more easy for the "Guest"
# sign-in option to demonstrate some entities being owned. In a regular org,
# a guest user would probably not be registered like this.
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest@example.com
    picture: https://avatars.dicebear.com/api/avataaars/guest@example.com.svg?background=%23fff
  memberOf: [platform-team]
